version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bookmyticket

    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    restart: always

    ports:
      - "6379:6379"

  bookmyticket:
    build: .

    container_name: bookmyticket

    ports:
      - "8085:8085"

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookmyticket?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_URL: redis://redis:6379
      APP_PASSWORD: ${APP_PASSWORD}
      CLOUDINARY_URL: ${CLOUDINARY_URL}